=== JoachimFalk/flummy/cmx.dtd
<!ELEMENT vpcconfiguration (resultfile?, measurefile?, resources, mappings, topology?)>

<!ELEMENT resultfile EMPTY>
<!ATTLIST resultfile
name CDATA #REQUIRED>

<!ELEMENT measurefile EMPTY>
<!ATTLIST measurefile
name CDATA #REQUIRED>

<!ELEMENT resources ((attribute)*, (component)*)>

<!ELEMENT component ((attribute)*)>
<!ATTLIST component
name ID #REQUIRED
type CDATA #IMPLIED
scheduler CDATA #REQUIRED>

<!ELEMENT attribute (attribute|parameter)*>
<!ATTLIST attribute 
type CDATA #REQUIRED
value CDATA #IMPLIED>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
type CDATA #REQUIRED
value CDATA #REQUIRED>

<!ELEMENT mappings (mapping)*>

<!ELEMENT mapping (attribute|timing)*>
<!ATTLIST mapping
source CDATA #REQUIRED
target IDREF #REQUIRED>

<!ELEMENT timing EMPTY>
<!ATTLIST timing
powermode CDATA #IMPLIED
delay   CDATA #IMPLIED
dii     CDATA #IMPLIED
latency CDATA #IMPLIED
fname   CDATA #IMPLIED>

<!ELEMENT topology (route)*>
<!ATTLIST topology
tracing     CDATA #IMPLIED
>
<!ELEMENT route (hop)*>
<!ATTLIST route
source      CDATA #REQUIRED
destination CDATA #REQUIRED
type        CDATA #IMPLIED
tracing     CDATA #IMPLIED
>

<!ELEMENT hop (timing|attribute)*>
<!ATTLIST hop
name    CDATA #IMPLIED>

=== JoachimFalk/flummy/systemoc-sqr/configuration.cmx.xml
<?xml version="1.0"?>
<!DOCTYPE vpcconfiguration SYSTEM "cmx.dtd">
<vpcconfiguration>
 <resultfile name=""/>
 <measurefile name=""/>

 <resources>
  <component name="Component1" type="threaded" scheduler="RoundRobin">
   <attribute type="timeslice" value="20ns"/>
  </component>

  <component name="ZeroCom" type="threaded" scheduler="FCFS"></component>
 </resources>

 <mappings>
  <mapping source="sqrroot.a1" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="Src::src" value="100"/>
  </mapping>

  <mapping source="sqrroot.a2" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="SqrLoop::copyStore"  value="100"/>
    <attribute type="SqrLoop::copyInput"  value="100"/>
    <attribute type="SqrLoop::copyApprox" value="100"/>
  </mapping>

  <mapping source="sqrroot.a3" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="Approx::approx" value="100"/>
  </mapping>

  <mapping source="sqrroot.a4" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="Dup::dup" value="100"/>
  </mapping>

  <mapping source="sqrroot.a5" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="Sink::sink" value="100"/>
  </mapping>

  <mapping source="cf_sqrroot.a1_sqrroot.a2_1" target="ZeroCom">
    <timing delay="0"/>
  </mapping>

  <mapping source="cf_sqrroot.a2_sqrroot.a3_1" target="ZeroCom">
    <timing delay="0"/>
  </mapping>

  <mapping source="cf_sqrroot.a3_sqrroot.a4_1" target="ZeroCom">
    <timing delay="0"/>
  </mapping>

  <mapping source="cf_sqrroot.a4_sqrroot.a3_1" target="ZeroCom">
    <timing delay="0"/>
  </mapping>

  <mapping source="cf_sqrroot.a4_sqrroot.a2_1" target="ZeroCom">
    <timing delay="0"/>
  </mapping>

  <mapping source="cf_sqrroot.a2_sqrroot.a5_1" target="ZeroCom">
    <timing delay="0"/>
  </mapping>

 </mappings>
</vpcconfiguration>

=== JoachimFalk/flummy/vpc/automotive-energy/vpc/sqr.vpc.xml
<?xml version="1.0"?>
<!DOCTYPE vpcconfiguration SYSTEM "cmx.dtd">
<vpcconfiguration>

 <resources>
  <component name="CPU" scheduler="PS">
   <attribute type="powermode">
     <attribute type="FAST">
	   <parameter type="IDLE"     value="0.05 mW" />
	   <parameter type="STALLED"  value="0.50 mW" />
	   <parameter type="RUNNING"  value="1.00 mW" />
	   <parameter type="transaction_delay" value="1 ns"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0.01 mW" />
	   <parameter type="STALLED"  value="0.11 mW" />
	   <parameter type="RUNNING"  value="0.21 mW" />
	   <parameter type="transaction_delay" value="3 ns"/>
	 </attribute>
   </attribute>
  </component>

  <component name="Bus" scheduler="PS">
   <attribute type="powermode">
     <attribute type="FAST">
	   <parameter type="IDLE"     value="0.06 mW" />
	   <parameter type="STALLED"  value="0.60 mW" />
	   <parameter type="RUNNING"  value="1.00 mW" />
	   <parameter type="transaction_delay" value="1 ns"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0.02 mW" />
	   <parameter type="STALLED"  value="0.12 mW" />
	   <parameter type="RUNNING"  value="0.22 mW" />
	   <parameter type="transaction_delay" value="3 ns"/>
	 </attribute>
   </attribute>
  </component>

  <component name="Mem" scheduler="PS">
    <attribute type="powermode">
     <attribute type="FAST">
	   <parameter type="IDLE"     value="0.07 mW" />
	   <parameter type="STALLED"  value="0.70 mW" />
	   <parameter type="RUNNING"  value="1.00 mW" />
	   <parameter type="transaction_delay" value="1 ns"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0.03 mW" />
	   <parameter type="STALLED"  value="0.13 mW" />
	   <parameter type="RUNNING"  value="0.23 mW" />
	   <parameter type="transaction_delay" value="3 ns"/>
	 </attribute>
   </attribute>
  </component>
 </resources>


 <mappings>
  <mapping source="sqrroot.a1" target="CPU">
    <timing delay="1 ns"  powermode="FAST"/>
    <timing delay="10 ns" powermode="SLOW"/>
    <timing fname="Src::src" delay="1 ns"   powermode="FAST"/>
    <timing fname="Src::src" delay="10 ns"  powermode="SLOW"/>
  </mapping>

  <mapping source="sqrroot.a2" target="CPU">
	<timing delay="1 ns"  powermode="FAST"/>
    <timing delay="10 ns" powermode="SLOW"/>
    <timing fname="Sink::sink" delay="23 ns"  powermode="FAST"/>
    <timing fname="Sink::sink" delay="27 ns"  powermode="SLOW"/> 
  </mapping>

  <mapping source="sqrroot.a3" target="CPU">
    <timing delay="1 ns"  powermode="FAST"/>
    <timing delay="10 ns" powermode="SLOW"/>
  </mapping>
 </mappings>
 
 
 <topology tracing="true" default="ignore">
  <route source="sqrroot.a1" destination="cf_sqrroot.a1_sqrroot.a2_1" tracing="false">
    <hop name="CPU" />
    <hop name="Bus" />
    <hop name="Mem" />
  </route>
  <route source="cf_sqrroot.a1_sqrroot.a2_1" destination="sqrroot.a2">
    <hop name="Mem" />
    <hop name="Bus" />
    <hop name="CPU" />
  </route>
 </topology>
 
</vpcconfiguration>

=== JoachimFalk/flummy/systemoc-sqr/pipelining.cmx.xml
<?xml version="1.0"?>
<!DOCTYPE vpcconfiguration SYSTEM "cmx.dtd">
<vpcconfiguration>
 <resultfile name=""/>
 <measurefile name=""/>

 <resources>
  <component name="Component1" type="threaded" scheduler="RoundRobin">
   <attribute type="timeslice" value="20ns"/>
  </component>
  <component name="FIFO" type="threaded" scheduler="RoundRobin">
   <attribute type="timeslice" value="20ns"/>
  </component>
 </resources>

 <mappings>
  <mapping source="sqrroot.a1" target="Component1">
    <timing dii="31" latency="33"/>
    <timing dii="13" latency="19" fname="Src::src"/>
  </mapping>

  <mapping source="sqrroot.a2" target="Component1">
    <timing dii="10" latency="100"/>
    <timing dii="10" latency="13" fname="SqrLoop::copyStore"/>
    <timing dii="7"  latency="17" fname="SqrLoop::copyInput"/>
    <timing dii="13" latency="19" fname="SqrLoop::copyApprox"/>
  </mapping>

  <mapping source="sqrroot.a3" target="Component1">
    <timing dii="100" latency="133"/>
    <timing dii="77"  latency="77" fname="Approx::approx"/>
  </mapping>

  <mapping source="sqrroot.a4" target="Component1">
    <timing dii="31" latency="33"/>
    <timing dii="11" latency="13" fname="Dup::dup"/>
  </mapping>

  <mapping source="sqrroot.a5" target="Component1">
    <timing dii="31" latency="33"/>
    <timing dii="13" latency="19" fname="Sink::sink"/>
  </mapping>

  <mapping source="sqrroot.smoc_fifo_0" target="FIFO">
    <timing dii="7" latency="37"/>
  </mapping>

  <mapping source="sqrroot.smoc_fifo_1" target="FIFO">
    <timing dii="11" latency="31"/>
  </mapping>

  <mapping source="sqrroot.smoc_fifo_2" target="FIFO">
    <timing dii="3" latency="42"/>
  </mapping>

  <mapping source="sqrroot.smoc_fifo_3" target="FIFO">
    <timing dii="2" latency="17"/>
  </mapping>

  <mapping source="sqrroot.smoc_fifo_4" target="FIFO">
    <timing dii="5" latency="55"/>
  </mapping>

  <mapping source="sqrroot.smoc_fifo_5" target="FIFO">
    <timing dii="1" latency="21"/>
  </mapping>

 </mappings>
</vpcconfiguration>

=== JoachimFalk/flummy/vpc/dynamic-dse/vpc/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vpcconfiguration SYSTEM "cmx.dtd">

<vpcconfiguration>
  <resources>
    <component name="ECU" scheduler="PSNOPRE">
      <attribute type="transaction">
        <parameter type="delay" value="200 us" />
        <parameter type="size" value="1" />
      </attribute>
      <attribute type="powermode">
        <attribute type="SLOW">
          <parameter type="RUNNING" value="20.0 mW" />
          <parameter type="IDLE" value="5.0 mW" />
          <parameter type="STALLED" value="5.0 mW" />
        </attribute>
      </attribute>
       <attribute type="multicastgroup" value="msg">
  	<attribute type="task" value="msg_top.test_2_msg_rec1"/>
	<attribute type="task" value="msg_top.test_2_msg_rec2"/>
       </attribute>
       <attribute type="multicastgroup" value="msg2">
	<attribute type="task" value="msg_top.test2_2_msg2_rec3"/>
	<attribute type="task" value="msg_top.test2_2_msg2_rec4"/>
	<attribute type="task" value="msg_top.test2_2_msg2_rec5"/>
	<attribute type="task" value="msg_top.test2_2_msg2_rec6"/>
  </attribute>
    </component>
     </resources>
  <mappings>
    <mapping source="top.test" target="ECU">
      <timing delay="42.857142857142854us" />
    </mapping>
	<mapping source="top.rec1" target="ECU">
      <timing delay="42.857142857142854us" />
    </mapping>
    <mapping source="top.rec2" target="ECU">
      <timing delay="42.857142857142854us" />
    </mapping>
    <mapping source="top.test2" target="ECU">
      <timing delay="42.857142857142854us" />
    </mapping>
    <mapping source="top.rec3" target="ECU">
      <timing delay="42.857142857142854us" />
    </mapping>
    <mapping source="top.rec4" target="ECU">
      <timing delay="42.857142857142854us" />
    </mapping>
    <mapping source="top.rec5" target="ECU">
      <timing delay="42.857142857142854us" />
    </mapping>
    <mapping source="top.rec6" target="ECU">
      <timing delay="42.857142857142854us" />
    </mapping>
  </mappings>
  <topology tracing="true">
 <route source="top.test" destination="msg_rec1">
  <hop name="ECU">        <timing dii="10" latency="10" /> </hop>
</route>
 <route source="msg_rec1" destination="top.rec1"/>
 <route source="top.test" destination="msg_rec2">
 <hop name="ECU">        <timing dii="10" latency="10" /> </hop>
</route>
<route source="msg_rec2" destination="top.rec2"/>
 <route source="top.test2" destination="msg2_rec3">
 <hop name="ECU">        <timing dii="10" latency="10" /> </hop>
</route>
<route source="msg2_rec3" destination="top.rec3"/>
 <route source="top.test2" destination="msg2_rec4">
 <hop name="ECU">        <timing dii="10" latency="10" /> </hop>
</route>
<route source="msg2_rec4" destination="top.rec4"/>
 <route source="top.test2" destination="msg2_rec5">
 <hop name="ECU">        <timing dii="10" latency="10" /> </hop>
</route>
<route source="msg2_rec5" destination="top.rec5"/>
 <route source="top.test2" destination="msg2_rec6">
 <hop name="ECU">        <timing dii="10" latency="10" /> </hop>
</route>
<route source="msg2_rec6" destination="top.rec6"/>


  </topology>
</vpcconfiguration>

=== JoachimFalk/flummy/vpc/automotive-testcase/vpc/configuration_AP25_V1.vpc.xml
<?xml version="1.0"?>
<!DOCTYPE vpcconfiguration SYSTEM "cmx.dtd">
<vpcconfiguration>
 <resultfile name=""/>
 <measurefile name=""/>

 <resources>
  <component name="SG1" type="threaded" scheduler="PS">
    <attribute type="transaction_delay" value="50us" />
  </component>

  <component name="SG2" type="threaded" scheduler="PS">
    <attribute type="transaction_delay" value="8us" />
  </component>

  <component name="SG3" type="threaded" scheduler="PS">
    <attribute type="transaction_delay" value="1us" />
  </component>
  
  
  <component name="Switch1" type="threaded" scheduler="PS">
  	<attribute type="transaction">
  		<parameter type="delay" value="0.083333336 us" />
    	<parameter type="size" value="1" />
  	</attribute>
  </component>
  <component name="Switch2" type="threaded" scheduler="FCFS">
    <attribute type="transaction">
        <parameter type="delay" value="0.083333336 us" />
        <parameter type="size" value="1" />
    </attribute>
  </component>
  
  <component name="sg1_eth1" scheduler="AVB">
    <attribute type="1" value="0.5"></attribute>
    <attribute type="2" value="0.2"></attribute>
    <attribute type="transaction">
        <parameter type="delay" value="2 us" />
        <parameter type="size" value="1" />
    </attribute>
  </component>
  <component name="eth1_eth2" scheduler="AVB">
    <attribute type="1" value="0.2"></attribute>
    <attribute type="2" value="0.5"></attribute>
    <attribute type="transaction">
        <parameter type="delay" value="2 us" />
        <parameter type="size" value="1" />
    </attribute>
  </component>
  <component name="eth2_sg2" scheduler="AVB">
    <attribute type="1" value="0.5"></attribute>
    <attribute type="2" value="0.2"></attribute>
    <attribute type="transaction">
        <parameter type="delay" value="2 us" />
        <parameter type="size" value="1" />
    </attribute>
  </component>
  
  <component name="ZeroCom" scheduler="PS">
    <attribute type="transaction_delay" value="0us" />
  </component>

  <component name="ZeroCom2" scheduler="PS">
    <attribute type="transaction_delay" value="0us" />
  </component>

 </resources>

 <mappings>
  <mapping source="TTGraph.Producer_44,1kHz" target="SG1">
    <timing delay="1us"/>
  </mapping>

  <mapping source="TTGraph.Player_44,1kHz" target="SG2">
    <timing delay="5us"/>
  </mapping>

  <mapping source="TTGraph.Send_1722" target="SG1">
    <timing delay="5us"/>
  </mapping>
  
  <mapping source="TTGraph.Receive_1722" target="SG2">      
    <timing delay="5us"/>
  </mapping>  
  <mapping source="TTGraph.Traffic1" target="eth1_eth2">
    <timing delay="114.4us"/>
  </mapping>
    <mapping source="TTGraph.Traffic2" target="eth1_eth2">
    <timing delay="114.4us"/>
  </mapping>
    <mapping source="TTGraph.Traffic3_consume" target="ZeroCom">
    <timing delay="4us"/>
  </mapping>  
  <mapping source="TTGraph.Traffic3_send" target="ZeroCom">
    <timing delay="1us"/>
  </mapping>
 </mappings>
 <topology tracing="true">
 
   <route  source="TTGraph.Producer_44,1kHz" destination="channel1" tracing="false">
   </route>   
   <route  source="channel1" destination="TTGraph.Send_1722">
   </route>

   <route  source="TTGraph.Send_1722" destination="channel2_2">
	 <hop name="sg1_eth1">  <timing dii="8.39us" latency="8.39us" />  <attribute type="priority" value="2" />   
     </hop>
	 <hop name="Switch1">  <timing dii="17.49ns" latency="17.49ns" /> </hop>
	 <hop name="eth1_eth2">  <timing dii="8.39us" latency="8.39us" /> <attribute type="priority" value="2" /> </hop>
   	 <hop name="Switch2">  <timing dii="17.49ns" latency="17.49ns" /> </hop>
   	 <hop name="eth2_sg2">  <timing dii="8.39us" latency="8.39us" /> <attribute type="priority" value="2" /> </hop>
   </route>
   <route  source="channel2_2" destination="TTGraph.Receive_1722">
   </route>

   <route  source="TTGraph.Send_1722" destination="channel2_1">
	 <hop name="sg1_eth1">  <timing dii="7.78us" latency="7.78us" />  <attribute type="priority" value="2" />   
     </hop>
	 <hop name="Switch1">  <timing dii="16.21ns" latency="16.21ns" /> </hop>
	 <hop name="eth1_eth2">  <timing dii="7.78us" latency="7.78us" /> <attribute type="priority" value="2" /> </hop>
   	 <hop name="Switch2">  <timing dii="16.21ns" latency="16.21ns" /> </hop>
   	 <hop name="eth2_sg2">  <timing dii="7.78us" latency="7.78us" /> <attribute type="priority" value="2" /> </hop>
   </route>
   <route  source="channel2_1" destination="TTGraph.Receive_1722">
   </route>

   
   <route  source="TTGraph.Receive_1722" destination="channel3">
   </route>
   <route  source="channel3" destination="TTGraph.Player_44,1kHz">
   </route>
   
   <route  source="TTGraph.Traffic3_send" destination="channelTraffic3" tracing="true">
	 <hop name="Switch1">  <timing dii="8ns" latency="8ns" /> </hop>
	 <hop name="eth1_eth2">  <timing dii="4us" latency="4us" /> <attribute type="priority" value="2" /> </hop>
   	 <hop name="Switch2">  <timing dii="8ns" latency="8ns" /> </hop>
	 <hop name="ZeroCom2">  <timing dii="8ns" latency="8ns" /> </hop>
   </route>
   <route  source="channelTraffic3" destination="TTGraph.Traffic3_consume">
   </route>
   
  </topology>
</vpcconfiguration>
